DROP DATABASE IF EXISTS bdempresa;
CREATE DATABASE IF NOT EXISTS bdempresa;
USE BDEmpresa;

/*************   TABLA DEPARTAMENTOS
                                      ******************/

DROP TABLE IF EXISTS DEPARTAMENTO;
CREATE TABLE IF NOT EXISTS DEPARTAMENTO(
	NUM_DEPARTAMENTO INT UNSIGNED auto_increment NOT NULL,
    NOME_DEPARTAMENTO VARCHAR(25) NOT NULL,
    /*****************************************************/
    PRIMARY KEY (NUM_DEPARTAMENTO),
    UNIQUE INDEX (NOME_DEPARTAMENTO),
    /****************RELACION DIRIGIR********************/
    NSS_DIRIGE VARCHAR(15) NULL,
    DATA_DIRECCION DATE NULL
)ENGINE INNODB;

/*************   TABLA PROXECTOS
                                      ******************/
DROP TABLE IF EXISTS PROXECTO;
CREATE TABLE IF NOT EXISTS PROXECTO(
	NUM_PROXECTO INT UNSIGNED NOT NULL,
    NOME_PROXECTO VARCHAR(25) NOT NULL,
    LUGAR VARCHAR(25) NOT NULL,
    /***************************************************/
    PRIMARY KEY (NUM_PROXECTO),
    UNIQUE INDEX (NOME_PROXECTO),
    /***********RELACION TENER DEPARTAMENTO************/
    NUM_DEPARTAMENTO INT UNSIGNED NOT NULL,
    FOREIGN KEY (NUM_DEPARTAMENTO) REFERENCES DEPARTAMENTO(NUM_DEPARTAMENTO)
		ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    INDEX FK_NUM_DEPARTAMENTO(NUM_DEPARTAMENTO)    
)ENGINE INNODB;


/*************   TABLA EMPREGADO
                                      ******************/
DROP TABLE IF EXISTS EMPREGADO;
CREATE TABLE IF NOT EXISTS EMPREGADO(
	NOME VARCHAR(25) NOT NULL,
    APELIDO_1 VARCHAR(25) NOT NULL,
    APELIDO_2 VARCHAR(25) NOT NULL,
	NSS VARCHAR(15) NOT NULL,
    RUA VARCHAR(30) NULL,
    NUMERO_RUA INT NULL,
    PISO VARCHAR(4) NULL,
    CP CHAR(5) NULL,
    LOCALIDADE VARCHAR(25) NULL,
    DATA_NACEMENTO DATE NULL,
    SALARIO FLOAT NULL,
    SEXO CHAR(1) NULL,
    /*********************************/
    PRIMARY KEY(NSS),
    /********RELACION SUPERVISAR*******/
    NSS_SUPERVISA VARCHAR(15) NULL,
    FOREIGN KEY (NSS_SUPERVISA) REFERENCES EMPREGADO(NSS)
		ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    INDEX FK_SUPERVISOR(NSS_SUPERVISA),
    /*********RELACION TENER DEPARTAMENTO**********/
    NUM_DEPARTAMENTO_PERTENECE INT UNSIGNED NULL,
    FOREIGN KEY (NUM_DEPARTAMENTO_PERTENECE) REFERENCES DEPARTAMENTO(NUM_DEPARTAMENTO)
		ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    INDEX FK_DEPARTAMENTO(NUM_DEPARTAMENTO_PERTENECE)
)ENGINE INNODB;                                      

/*************   TABLA EMPREGADO_PROXECTO
                                      ******************/
DROP TABLE IF EXISTS EMPREGADO_PROXECTO;
CREATE TABLE IF NOT EXISTS EMPREGADO_PROXECTO(
	NSS_EMPREGADO VARCHAR(15) NOT NULL,
    NUM_PROXECTO INT UNSIGNED NOT NULL,
    HORAS_SEMANAS INT NULL
)ENGINE INNODB;

ALTER TABLE DEPARTAMENTO
	ADD FOREIGN KEY (NSS_DIRIGE) REFERENCES EMPREGADO(NSS)
		ON DELETE NO ACTION
        ON UPDATE NO ACTION,
	ADD INDEX FK_NSS_DIRIGE(NSS_DIRIGE);
    
 


