DROP DATABASE IF EXISTS EMPRESA;
CREATE DATABASE IF NOT EXISTS EMPRESA;
USE EMPRESA;

/*************   TABLA EMPREGADOS
                                      ******************/
DROP TABLE IF EXISTS EMPREGADOS;
CREATE TABLE IF NOT EXISTS EMPREGADOS(
	NOME VARCHAR(25) NOT NULL,
    APELIDO_1 VARCHAR(25) NOT NULL,
    APELIDO_2 VARCHAR(25) NOT NULL,
	NSS VARCHAR(15) NOT NULL,
    RUA VARCHAR(30) NULL,
    NUMERO_RUA INT NULL,
    PISO VARCHAR(4) NULL,
    CP CHAR(5) NULL,
    LOCALIDADE VARCHAR(25) NULL,
    DATA_NACEMENTO DATE NULL,
    SALARIO FLOAT NULL,
    SEXO CHAR(1) NULL,
    /*********************************/
    PRIMARY KEY(NSS),
    /********RELACION SUPERVISAR*******/
    NSS_SUPERVISA VARCHAR(15) NULL,
    FOREIGN KEY (NSS_SUPERVISA) REFERENCES EMPREGADOS(NSS)
		ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    INDEX FK_SUPERVISOR(NSS_SUPERVISA),
    /*********RELACION TENER DEPARTAMENTO**********/
    NUM_DEPARTAMENTO_PERTENECE INT NULL,
    FOREIGN KEY (NUM_DEPARTAMENTO_PERTENECE) REFERENCES DEPARTAMENTOS(NUM_DEPARTAMENTO),
    INDEX FK_DEPARTAMENTO(NUM_DEPARTAMENTO_PERTENECE)
)ENGINE INNODB;                                      

/*************   TABLA DEPARTAMENTOS
                                      ******************/

DROP TABLE IF EXISTS DEPARTAMENTOS;
CREATE TABLE IF NOT EXISTS DEPARTAMENTOS(
	NUM_DEPARTAMENTO INT UNSIGNED auto_increment NOT NULL,
    NOME_DEPARTAMENTO VARCHAR(25) NOT NULL,
    /*****************************************************/
    PRIMARY KEY (NUM_DEPARTAMENTO),
    /****************RELACION DIRIGIR********************/
    NSS_DIRIGE VARCHAR(15) NULL,
    DATA_DIRECCION DATE NULL,
    FOREIGN KEY (NSS_DIRIGE) REFERENCES EMPREGADOS(NSS)
		ON DELETE NO ACTION
        ON UPDATE NO ACTION,
	INDEX FK_NSS_DIRIGE(NSS_DIRIGE)
)ENGINE INNODB;